### ISSUE TITLE
CCNetConfig long time no update 

### ISSUE THREAD

**Issue by easonjim** [camalot/ccnetconfig#1]
Dear author, I have found that this project has not been updated for a long time, but now I still need to use CCNET, so, I would be able to maintain your project?

**Comment by camalot** [comment]
sorry @easonjim, I've been busy 😉 , are you still interested in maintaining this project?

**Comment by easonjim** [comment]
Dear @camalot ,sorry i see your message in this time;
but,i turned to Jenkins now.
